version: '3.8'
services:
  gateway:
    build:
      context: .
      dockerfile: microservices/gateway/Dockerfile
    environment:
      GATEWAY_PORT: 3001
      AUTH_URL: http://auth:3002
      SERVICE_URL: http://service:3003
      BOOKING_URL: http://booking:3004
      DESIGNER_URL: http://designer:3005
      TRANSACTION_URL: http://transaction:3006
      REVIEW_URL: http://review:3007
      GALLERY_URL: http://gallery:3008
    ports:
      - "3001:3001"
    depends_on:
      - auth
      - service
      - booking
      - designer
      - transaction
      - review
      - gallery
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
  auth:
    build:
      context: .
      dockerfile: microservices/auth/Dockerfile
    environment:
      AUTH_PORT: 3002
      DATABASE_URL: sqlserver://host.docker.internal:1433;database=NailSalon;user=sa;password=Your_password123;trustservercertificate=true
    ports:
      - "3002:3002"
    depends_on:
      - db
  service:
    build:
      context: .
      dockerfile: microservices/service/Dockerfile
    environment:
      SERVICE_PORT: 3003
      DATABASE_URL: sqlserver://host.docker.internal:1433;database=NailSalon;user=sa;password=Your_password123;trustservercertificate=true
    ports:
      - "3003:3003"
    depends_on:
      - db
  booking:
    build:
      context: .
      dockerfile: microservices/booking/Dockerfile
    environment:
      BOOKING_PORT: 3004
      DATABASE_URL: sqlserver://host.docker.internal:1433;database=NailSalon;user=sa;password=Your_password123;trustservercertificate=true
    ports:
      - "3004:3004"
    depends_on:
      - db
  designer:
    build:
      context: .
      dockerfile: microservices/designer/Dockerfile
    environment:
      DESIGNER_PORT: 3005
      DATABASE_URL: sqlserver://host.docker.internal:1433;database=NailSalon;user=sa;password=Your_password123;trustservercertificate=true
    ports:
      - "3005:3005"
    depends_on:
      - db
  transaction:
    build:
      context: .
      dockerfile: microservices/transaction/Dockerfile
    environment:
      TRANSACTION_PORT: 3006
      DATABASE_URL: sqlserver://host.docker.internal:1433;database=NailSalon;user=sa;password=Your_password123;trustservercertificate=true
    ports:
      - "3006:3006"
    depends_on:
      - db
  review:
    build:
      context: .
      dockerfile: microservices/review/Dockerfile
    environment:
      REVIEW_PORT: 3007
      DATABASE_URL: sqlserver://host.docker.internal:1433;database=NailSalon;user=sa;password=Your_password123;trustservercertificate=true
    ports:
      - "3007:3007"
    depends_on:
      - db
  gallery:
    build:
      context: .
      dockerfile: microservices/gallery/Dockerfile
    environment:
      GALLERY_PORT: 3008
      DATABASE_URL: sqlserver://host.docker.internal:1433;database=NailSalon;user=sa;password=Your_password123;trustservercertificate=true
    ports:
      - "3008:3008"
    depends_on:
      - db
